import re
import json
import pandas as pd
from typing import List, Dict, Any

from utils import keywords


def filter_tables_re(table, pattern, reFlags=re.NOFLAG) -> bool: 
    """function to see if table contains a regex pattern in any location

    Args:
        table (docling table item): 
        pattern (regex pattern): 
        reFlags (regex flag, optional): regex flag as defined in python re module. Defaults to re.NOFLAG.

    Returns:
        bool: if pattern is persent in table
    """
    return any(re.search(pattern, text["text"], reFlags) for text in table["data"]["table_cells"])

def extract_table_to_df(table) -> pd.DataFrame: 
    """turns a docling table object into a pandas dataframe
    - in the case a cell is larger than the smallest cell, this code copies it into every position
      - more generally, docling defines a start/end row/col idx, this code copies it to all of those cells

    Args:
        table (docling table object):

    Returns:
        pd.DataFrame: 
    """
    nrows = table['data']['num_rows']
    ncols = table['data']['num_cols']
    arr_table = [["" for _ in range(ncols)] for _ in range(nrows)]
    for item in table['data']['table_cells']: 
        start_row = item['start_row_offset_idx']
        end_row = item['end_row_offset_idx']
        start_col = item['start_col_offset_idx']
        end_col = item['end_col_offset_idx']
        text = item['text']
        for r in range(start_row, end_row):
            for c in range(start_col, end_col):
                if arr_table[r][c] == '':  # Only fill if empty
                    arr_table[r][c] = text
    return pd.DataFrame(arr_table)


def get_tableref_per_keyword(document, patterns = keywords.QUANT_PATTERNS, reFlag = re.IGNORECASE):
    """takes in a document and a dictionary of section: regex pattern and returns the list of table refs per keyword

    Args:
        document (docling documnet): the full json object generated by docling
        patterns (Dict[str, regex_pattern], optional): dictionary of category to regex patterns. Defaults to keywords.QUANT_PATTERNS.
        reFlag (regex flag, optional): flag as defined by re module. Recommended to be re.IGNORECASE . Defaults to re.IGNORECASE.

    Returns:
        Dict[str, list[str]]: _description_
    """
    tables = document['tables']
    per_keyword_tables = {
        k: [t['self_ref'] for t in tables if  filter_tables_re(t, v, reFlag )] 
        for k,v in patterns.items()
    } # each keyword has a regex pattern defined for it, for each keyword we collect all tables relevant to its category
    return per_keyword_tables

def main(document, patterns = keywords.QUANT_PATTERNS):
    """
    Example code that takes a document and optionally a Dict[name, regex pattern] and returns table_refs that match
    - includes redundant items 'all keywords' and 'keywords missing tables' for convinence
    Returns: 
    {
        per keyword table refs : {patterns.keys() : list of table_refs for matching keys}, 
        all table refs : [list of all table refs found to be relevant], 
        keywords missing tables : list of keywords where no table ref found         
    }
    """ 
    tables = document['tables']
    per_keyword_tables = {
        k: [t['self_ref'] for t in tables if  filter_tables_re(t, v, re.IGNORECASE)] 
        for k,v in patterns.items()
    } # each keyword has a regex pattern defined for it, for each keyword we collect all tables relevant to its category
    relevant_tables = list({ref for refs in per_keyword_tables.values() for ref in refs}) # all tables found to be relevant
    keywords_missing_tables = [k for k,v in per_keyword_tables.items() if not(v) ] # all keywords that had no matches
    
    return {
        "per keyword table refs": per_keyword_tables, 
        "all table refs": list(relevant_tables), 
        "keywords missing tables": list(keywords_missing_tables)
    }